---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 1f2f0f42f392275b3abb0250dcd0fbc337f12e4a
    app.quarkus.io/vcs-uri: https://github.com/akoserwal/qechoapp.git
    app.quarkus.io/build-timestamp: 2024-01-06 - 10:23:35 +0000
  labels:
    app.kubernetes.io/name: qechoapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: qechoapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: qechoapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 1f2f0f42f392275b3abb0250dcd0fbc337f12e4a
    app.quarkus.io/vcs-uri: https://github.com/akoserwal/qechoapp.git
    app.quarkus.io/build-timestamp: 2024-01-06 - 10:23:35 +0000
  labels:
    app.kubernetes.io/name: qechoapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: qechoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qechoapp
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 1f2f0f42f392275b3abb0250dcd0fbc337f12e4a
        app.quarkus.io/vcs-uri: https://github.com/akoserwal/qechoapp.git
        app.quarkus.io/build-timestamp: 2024-01-06 - 10:23:35 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: qechoapp
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/akoserwal/qechoapp:v1.0
          imagePullPolicy: Always
          name: qechoapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
